export const UPDATE_LOGGED_IN_USER: string = 'UPDATE_LOGGED_IN_USER';
export const LOGOUT: string = 'LOGOUT';
export const BEER_ADDED_TO_INVENTORY: string = 'BEER_ADDED_TO_INVENTORY';
export const BEER_UPDATE_INVENTORY_QUANTITY: string =
  'BEER_UPDATE_INVENTORY_QUANTITY';
